[package]
name = "jtalk_wrap"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.5"
reqwest = { version = "0.11", features = ["cookies"] }
scraper = "0.12.0"
serde = { version = "1.0.135", features = ["derive"] }
tokio = { version = "1.16.1", features = ["full"] }
